version: 2

sources:
  - name: raw
    description: Raw data from CSV files loaded into PostgreSQL
    tables:
      - name: customers
        description: Customer information from the e-commerce platform
        columns:
          - name: customer_id
            description: Unique identifier for customers
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - not_null
              - unique
          - name: registration_date
            description: Date when customer registered
            tests:
              - not_null

      - name: products
        description: Product catalog information
        columns:
          - name: product_id
            description: Unique identifier for products
            tests:
              - unique
              - not_null
          - name: product_name
            description: Name of the product
            tests:
              - not_null
          - name: price
            description: Product price in USD
            tests:
              - not_null

      - name: orders
        description: Order transactions from customers
        columns:
          - name: order_id
            description: Unique identifier for orders
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Reference to customer who placed the order
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'customers')
                  field: customer_id
          - name: product_id
            description: Reference to ordered product
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'products')
                  field: product_id

      - name: visits
        description: Website visit tracking data
        columns:
          - name: visit_id
            description: Unique identifier for visits
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Reference to visiting customer
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'customers')
                  field: customer_id

models:
  - name: stg_customers
    description: Cleaned and standardized customer data
    columns:
      - name: customer_id
        description: Unique identifier for customers
        tests:
          - unique
          - not_null
      - name: email
        description: Standardized customer email (lowercase, trimmed)
        tests:
          - unique
          - not_null

  - name: stg_products
    description: Cleaned and standardized product data
    columns:
      - name: product_id
        description: Unique identifier for products
        tests:
          - unique
          - not_null
      - name: price
        description: Product price as decimal
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned and standardized order data
    columns:
      - name: order_id
        description: Unique identifier for orders
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Reference to customer
        tests:
          - not_null
      - name: product_id
        description: Reference to product
        tests:
          - not_null

  - name: stg_visits
    description: Cleaned and standardized visit data
    columns:
      - name: visit_id
        description: Unique identifier for visits
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Reference to visiting customer
        tests:
          - not_null 