version: 2

models:
  - name: dim_customers
    description: Customer dimension table with aggregated metrics and segmentation
    columns:
      - name: customer_id
        description: Unique identifier for customers (primary key)
        tests:
          - unique
          - not_null
      - name: customer_segment
        description: Customer segmentation based on purchase behavior
      - name: total_orders
        description: Total number of orders placed by customer
      - name: total_spent
        description: Total amount spent by customer
      - name: conversion_rate_percent
        description: Percentage of visits that resulted in orders

  - name: dim_products
    description: Product dimension table with sales performance metrics
    columns:
      - name: product_id
        description: Unique identifier for products (primary key)
        tests:
          - unique
          - not_null
      - name: performance_tier
        description: Product performance classification based on sales
      - name: total_revenue
        description: Total revenue generated by this product
      - name: total_quantity_sold
        description: Total units sold of this product

  - name: dim_date
    description: Date dimension table for time-based analysis
    columns:
      - name: date_key
        description: Primary key - the actual date
        tests:
          - unique
          - not_null
      - name: is_weekend
        description: Boolean flag indicating if date is weekend
      - name: quarter_name
        description: Quarter name (Q1, Q2, Q3, Q4) 